// @ts-check
import { defineConfig, passthroughImageService } from 'astro/config';
import starlight from '@astrojs/starlight';

// Patterson-branded Starlight documentation site.
//
// Branding is applied entirely through `src/styles/patterson.css`, which remaps
// Starlight's `--sl-*` custom properties onto Patterson brand tokens. No Starlight
// component is ejected, so the theme survives Starlight upgrades.
//
// https://astro.build/config
export default defineConfig({
  // CUSTOMIZE: set `site` to the deployed origin (used for canonical URLs,
  // sitemap, and social previews). Leave it unset until the target is known.
  // site: 'https://docs.example.com',
  //
  // CUSTOMIZE: when deploying to a sub-path (GitHub Pages project sites), also
  // set `base` to that path, e.g. base: '/my-docs'.
  // base: '/',

  // Astro's default image service compiles sharp, which carries an open advisory.
  // The passthrough service copies images through untouched — no native binary,
  // no optimization. Docs sites rarely need the pipeline.
  image: { service: passthroughImageService() },

  integrations: [
    starlight({
      // CUSTOMIZE: title, description, and tagline.
      title: 'Patterson Docs',
      description:
        'Documentation, guides, and reference for teams building on the Patterson Companies design system.',
      tagline: 'Trusted Expertise. Unrivaled Support.',
      logo: {
        light: './src/assets/patterson-logo-navy.svg',
        dark: './src/assets/patterson-logo-white.svg',
        replacesTitle: true,
      },
      favicon: '/favicon.svg',
      customCss: ['./src/styles/patterson.css'],
      // Proxima Nova is served by Adobe Fonts kit uth1qfm. Load it from the kit
      // only — Adobe's terms do not permit re-hosting Typekit payloads, so never
      // commit font binaries or @font-face declarations for it.
      head: [
        {
          tag: 'link',
          attrs: {
            rel: 'stylesheet',
            href: 'https://use.typekit.net/uth1qfm.css',
          },
        },
      ],
      social: [
        {
          icon: 'external',
          label: 'Patterson Companies',
          href: 'https://www.pattersoncompanies.com',
        },
      ],
      tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 3 },
      pagination: true,
      expressiveCode: {
        // Copy button on code frames; Patterson borders and radius come from
        // src/styles/patterson.css.
        frames: { showCopyToClipboardButton: true },
      },
      // Diataxis-flavored information architecture. Guides and Reference are
      // autogenerated from their folders, so a new file appears in the sidebar
      // with no config change.
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'Overview', link: '/' },
            { label: 'Getting started', link: '/getting-started/' },
          ],
        },
        {
          label: 'Guides',
          items: [{ autogenerate: { directory: 'guides' } }],
        },
        {
          label: 'Reference',
          items: [{ autogenerate: { directory: 'reference' } }],
        },
      ],
    }),
  ],
});
